FROM python:3.11-slim

# Установка системных зависимостей (если нужно для torch/transformers, но slim-версия минимизирует размер)
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем requirements и устанавливаем пакеты
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY . .

# Запуск приложения
CMD ["python", "app.py"]
